project:
  type: website

website:
  title: "ekhotone"
  favicon: objects/ekhotone_orb.png
  navbar:
    title: false
    logo: objects/ekhotone_horizontal_black.png
    right:
      - text: Articles
        href: articles.qmd

  page-footer: 
    left:
      - text: À propos de ce blog...
        href: about.qmd
    right: 
      - icon: github
        href: https://github.com/lucasvoirin/
      - icon: twitter 
        href: https://twitter.com/lucas_voirin
        
  twitter-card:
    title: ekhotone
    creator: "@lucas_voirin"
    image: objects/ekhotone_social.png
      
format:
  html:
    theme: theme.scss
    css: styles.css
    
language:
  search-detached-cancel-button-title: "Annuler"
  search: "Rechercher"
  search-matching-documents-text: "résultat(s)"
  search-no-results-text: "Pas de résultat"
  search-submit-button-title: "Soumettre"

editor: visual

