project:
  type: website

website:
  title: "ekhotone"
  favicon: objects/ekhotone_orb.png
  navbar:
    title: false
    logo: objects/ekhotone_horizontal_black.png
    right:
      - text: Articles
        href: articles.qmd

  page-footer: 
    left:
      - text: À propos de ce blog...
        href: about.qmd
    right: 
      - icon: github
        href: https://github.com/lucasvoirin/
      - icon: twitter 
        href: https://twitter.com/lucas_voirin
      
format:
  html:
    theme: theme.scss
    css: styles.css

editor: visual

